### PR TITLE
Update monorepo submodule

### PR DESCRIPTION
**Pull request by codyborn**
- Updated Monorepo submodule to latest master to pickup this change https://github.com/celo-org/celo-monorepo/pull/6251
  - This will fix the occasional ODIS out of quota issue 
- Small tweaks to readme

### CODE REVIEW

**Review by ErinHales — APPROVED** [review]
Looks good to me

**Comment by ErinHales** [comment]
Looks like we have some failing tests

**Review by carterqw2 — CHANGES_REQUESTED** [review]
I think it stopped building after the update.

**Comment by bowd** [comment]
I created a new `celo-monorepo` branch from the tag that Cody wanted to use + the hotifx for azure-hsm-wallets which we're still trying to figure out in devX.
Then I updated the komenci code to be in line with the changes to contractkit 1.0.0 and the monorepo restructuring.
The app builds now but we still need to test behaviour.

**Review by carterqw2 — APPROVED** [review]

**Comment by codyborn** [comment]
Thanks @bowd!

**Comment by bowd** [comment]
Ok tested this in alfajores with celo-monorepo updated to latest master + https://github.com/celo-org/celo-monorepo/pull/6829 and https://github.com/celo-org/celo-monorepo/pull/6010

Hopefully both of these will get merged soon so we can move to running off of master and post-release move to npm deps 🎉

**Pull request merged**
